---
name: Tox
on:
  schedule:
    - cron: '0 0 * * 0'
  push:
  pull_request:

jobs:
  test_tox:
    name: Run tox tests
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - '3.7'
          - '3.8'
          - '3.9'
          - '3.10'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: python -mpip install --upgrade wheel pytest tox
      - name: Get tox target
        id: toxtarget
        run: |
          py=$(echo ${{ matrix.python-version }} | tr -d .)
          echo "py=$py" >> $GITHUB_OUTPUT
      - name: Run tests
        run: tox -e py${{ steps.toxtarget.outputs.py }}
